version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes: 
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
  
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html

  backend:
    build: .
    restart: always
    volumes:
      - ./pkg:/app/pkg
      - ./cmd:/app/cmd
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./config:/app/config