apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: landingpage-dev
  namespace: example-tenant
spec:
  hosts:
  - landing-page.192-168-178-60.nip.io
  ports:
  - number: 3000
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: landingpage-dev
  namespace: example-tenant
spec:
  gateways:
    - dataspace/gateway
  hosts:
    - example-tenant.192-168-178-60.nip.io
  http:
  - timeout: 3s
    route:
      - destination:
          host: landing-page.192-168-178-60.nip.io
        weight: 100