apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: landingpage-dev
  namespace: core
spec:
  hosts:
  - landing-page.192-168-178-60.nip.io
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: landingpage-dev
  namespace: core
spec:
  gateways:
    - core/gateway
  hosts:
    - '*'
  http:
  - timeout: 3s
    match:
      - uri:
          prefix: /
    route:
      - destination:
          host: landing-page.192-168-178-60.nip.io
          port:
            number: 8080
        weight: 100