upstreamConfig:
  upstreams:
    - id: backend-provider
      path: ^/(api/portal/.*)$
      rewriteTarget: /$1
      uri: http://portal-provider:8080
    # - id: backend-consumer
    #   path: ^/(consumer/api/portal/.*)$
    #   rewriteTarget: /$1
    #   uri: http://portal-consumer:8080
    - id: registry
      path: ^/(api/registry/.*)$
      rewriteTarget: /$1
      passHostHeader: false
      # uri: https://mvp-ds.dev.mat.ptr.smartlivingnext.de
      uri: http://cors-proxy:3333
    - id: frontend-provider
      path: /
      uri: http://frontend:5173
    # - id: frontend-consumer
    #   path: /consumer
    #   uri: http://portal-consumer:8080
server:
  BindAddress: 0.0.0.0:4180
injectRequestHeaders:
  - name: X-Forwarded-Groups
    values:
      - claim: groups
  - name: X-Access-Token
    values:
      - claim: access_token
  - name: X-Forwarded-User
    values:
      - claim: user
  - name: X-Forwarded-Email
    values:
      - claim: email
  - name: X-Forwarded-Preferred-Username
    values:
      - claim: preferred_username
providers:
  - provider: keycloak-oidc
    id: keycloak
    clientID: "${CLIENT_ID}"
    clientSecret: "${CLIENT_SECRET}"
    scope: openid profile email offline_access
    oidcConfig:
      insecureAllowUnverifiedEmail: false
      issuerURL: "${ISSUER_URL}"
      emailClaim: email
      groupsClaim: groups
      userIDClaim: sub
      audienceClaims:
        - aud
