version: "3.9"

services:

  portal-provider:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - 5173:5173
    volumes:
      - ../src:/app/src
      - ../vite.config.ts:/app/vite.config.ts
      - ../package.json:/app/package.json
      - ../index.html:/app/index.html
      - ./portal/provider/config.js:/app/public/config.js
      - ./portal/borlabs-cookie-icon-dynamic.svg:/app/public/borlabs-cookie-icon-dynamic.svg
    depends_on:
      edc-provider:
        condition: service_healthy
        restart: true

  edc-provider:
    image: ghcr.io/connected-intelligent-systems/connector:v0.10.0
    ports:
      - 29291:19291
    volumes:
      - ./edc/vault.properties:/resources/vault.properties
      - ./edc/nodes.json:/resources/nodes.json
    environment:
      EDC_VAULT_FILE_PATH: /resources/vault.properties
      EDC_DSP_CALLBACK_ADDRESS: http://edc-provider:19194/protocol
      EDC_DATAPLANE_API_PUBLIC_BASEURL: http://localhost:29291/public
      EDC_WEB_REST_CORS_ENABLED: true
      EDC_WEB_REST_CORS_ORIGINS: "*"
      EDC_WEB_REST_CORS_HEADERS: Content-Type,Authorization
      EDC_WEB_REST_CORS_METHODS: GET,POST,OPTIONS
      WEB_HTTP_CATALOG_PORT: 19199
      WEB_HTTP_CATALOG_PATH: /catalog
      WEB_HTTP_PORT: 19191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 19193
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 19194
      WEB_HTTP_PROTOCOL_PATH: /protocol
      EDC_PUBLIC_KEY_ALIAS: public-key
      EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS: private-key
      EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS: public-key
      WEB_HTTP_PUBLIC_PORT: 19291
      WEB_HTTP_PUBLIC_PATH: /public
      WEB_HTTP_CONTROL_PORT: 19192
      WEB_HTTP_CONTROL_PATH: /control
      EDC_DATASOURCE_DEFAULT_URL: jdbc:postgresql://postgres:5432/dataspace?currentSchema=provider
      EDC_DATASOURCE_DEFAULT_USER: user
      EDC_DATASOURCE_DEFAULT_PASSWORD: postgres
      EDC_OAUTH_TOKEN_URL: http://keycloak:8080/realms/dataspace/protocol/openid-connect/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://keycloak:8080/realms/dataspace/protocol/openid-connect/certs
      EDC_OAUTH_CERTIFICATE_ALIAS: public-key
      EDC_OAUTH_PRIVATE_KEY_ALIAS: private-key
      EDC_OAUTH_CLIENT_ID: edc-provider
      EDC_OAUTH_PROVIDER_AUDIENCE: http://keycloak:8080/realms/dataspace
      EDC_OAUTH_VALIDATION_NBF_LEEWAY: 20
      EDC_OAUTH_VALIDATION_ISSUED_AT_LEEWAY: 5
      EDC_AGENT_IDENTITY_KEY: participant_id
      EDC_PARTICIPANT_ID: company1
      EDC_NODES_FILE_PATH: /resources/nodes.json
      EDC_SQL_SCHEMA_AUTOCREATE: true
    depends_on:
      keycloak:
        condition: service_healthy
        restart: true

  edc-consumer:
    image: ghcr.io/connected-intelligent-systems/connector:v0.10.0
    ports:
      - 19291:19291
    volumes:
      - ./edc/vault.properties:/resources/vault.properties
      - ./edc/nodes.json:/resources/nodes.json
    environment:
      EDC_VAULT_FILE_PATH: /resources/vault.properties
      EDC_DSP_CALLBACK_ADDRESS: http://edc-consumer:19194/protocol
      EDC_DATAPLANE_API_PUBLIC_BASEURL: http://localhost:19291/public
      EDC_WEB_REST_CORS_ENABLED: true
      EDC_WEB_REST_CORS_ORIGINS: "*"
      EDC_WEB_REST_CORS_HEADERS: Content-Type,Authorization
      EDC_WEB_REST_CORS_METHODS: GET,POST,OPTIONS
      WEB_HTTP_CATALOG_PORT: 19199
      WEB_HTTP_CATALOG_PATH: /catalog
      WEB_HTTP_PORT: 19191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 19193
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 19194
      WEB_HTTP_PROTOCOL_PATH: /protocol
      EDC_PUBLIC_KEY_ALIAS: public-key
      EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS: private-key
      EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS: public-key
      WEB_HTTP_PUBLIC_PORT: 19291
      WEB_HTTP_PUBLIC_PATH: /public
      WEB_HTTP_CONTROL_PORT: 19192
      WEB_HTTP_CONTROL_PATH: /control
      EDC_DATASOURCE_DEFAULT_URL: jdbc:postgresql://postgres:5432/dataspace?currentSchema=consumer
      EDC_DATASOURCE_DEFAULT_USER: user
      EDC_DATASOURCE_DEFAULT_PASSWORD: postgres
      EDC_OAUTH_TOKEN_URL: http://keycloak:8080/realms/dataspace/protocol/openid-connect/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://keycloak:8080/realms/dataspace/protocol/openid-connect/certs
      EDC_OAUTH_CERTIFICATE_ALIAS: public-key
      EDC_OAUTH_PRIVATE_KEY_ALIAS: private-key
      EDC_OAUTH_CLIENT_ID: edc-consumer
      EDC_OAUTH_PROVIDER_AUDIENCE: http://keycloak:8080/realms/dataspace
      EDC_OAUTH_VALIDATION_NBF_LEEWAY: 20
      EDC_OAUTH_VALIDATION_ISSUED_AT_LEEWAY: 5
      EDC_AGENT_IDENTITY_KEY: participant_id
      EDC_PARTICIPANT_ID: company2
      EDC_NODES_FILE_PATH: /resources/nodes.json
      EDC_SQL_SCHEMA_AUTOCREATE: true
    depends_on:
      keycloak:
        condition: service_healthy
        restart: true

  portal-consumer:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - 5174:5173
    volumes:
      - ../src:/app/src
      - ../vite.config.ts:/app/vite.config.ts
      - ../package.json:/app/package.json
      - ../index.html:/app/index.html
      - ./portal/consumer/config.js:/app/public/config.js
      - ./portal/borlabs-cookie-icon-dynamic.svg:/app/public/borlabs-cookie-icon-dynamic.svg
    environment:
      - VITE_EDC_MANAGEMENT_API_URL=http://edc-consumer:19193
      - VITE_EDC_PROTOCOL_API_URL=http://edc-consumer:19191
      - VITE_EDC_API_KEY=supersecret
    depends_on:
      edc-consumer:
        condition: service_healthy
        restart: true

  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataspace
    image: bitnamilegacy/postgresql:17.2.0
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    image: bitnamilegacy/keycloak:23.0.3
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_DATABASE_VENDOR=dev-file
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_EXTRA_ARGS='--import-realm'
      - KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
    volumes:
      - ./keycloak/realm-export-dataspace.json:/opt/bitnami/keycloak/data/import/dataspace-realm.json
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/realms/dataspace/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      start_interval: 30s
      start_period: 1s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
        