import { Labeled, FunctionField } from "react-admin";
import { Typography, Box, Link } from "@mui/material";

export const ProvenanceShow = () => {
  return (
    <Box>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
        Information about the origin and history of this asset. For more
        information, see the{" "}
        <Link
          href="https://www.w3.org/TR/prov-o/"
          target="_blank"
          rel="noopener noreferrer"
        >
          PROV-O Ontology
        </Link>
        .
      </Typography>

      <Labeled fullWidth label="Was Derived From">
        <FunctionField
          render={(record: any) =>
            record?.properties?.["http://www.w3.org/ns/prov#wasDerivedFrom"]?.[
              "@id"
            ] || "No source entity specified"
          }
        />
      </Labeled>

      <Labeled fullWidth label="Was Generated By">
        <FunctionField
          render={(record: any) =>
            record?.properties?.["http://www.w3.org/ns/prov#wasGeneratedBy"]?.[
              "http://purl.org/dc/terms/description"
            ] || "No activity description provided"
          }
        />
      </Labeled>

      <Labeled fullWidth label="Was Attributed To">
        <FunctionField
          render={(record: any) =>
            record?.properties?.["http://www.w3.org/ns/prov#wasAttributedTo"]?.[
              "@id"
            ] || "No agent specified"
          }
        />
      </Labeled>
    </Box>
  );
};
