upstreamConfig:
  upstreams:
    - id: backend
      path: ^/(api/user/.*)$
      rewriteTarget: /$1
      uri: http://backend:8080
    - id: registry
      path: ^/(api/registry/.*)$
      rewriteTarget: /$1
      passHostHeader: false
      uri: http://example-tenant.192-168-178-60.nip.io
    - id: frontend
      path: /
      uri: http://172.17.0.1:3000
server:
  BindAddress: 0.0.0.0:4180
injectRequestHeaders:
- name: X-Forwarded-Groups
  values:
  - claim: groups
- name: X-Access-Token
  values:
  - claim: access_token
- name: X-Forwarded-User
  values:
  - claim: user
- name: X-Forwarded-Email
  values:
  - claim: email
- name: X-Forwarded-Preferred-Username
  values:
  - claim: preferred_username
providers:
- provider: keycloak-oidc
  id: keycloak
  clientID: "${CLIENT_ID}"
  clientSecret: "${CLIENT_SECRET}"
  scope: openid profile email offline_access
  oidcConfig:
    insecureAllowUnverifiedEmail: false
    issuerURL: "${ISSUER_URL}"
    emailClaim: email
    groupsClaim: groups
    userIDClaim: sub
    audienceClaims: 
      - aud