import { TextInput, Labeled } from "react-admin";
import { Typography, Link, Box } from "@mui/material";

export const ProvenanceInput = () => {
  return (
    <Box sx={{ width: "100%" }}>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
        Describe the origin of the dataset. For more information, see the{" "}
        <Link
          href="https://www.w3.org/TR/prov-o/"
          target="_blank"
          rel="noopener noreferrer"
        >
          PROV-O Ontology
        </Link>
        .
      </Typography>
      <Labeled label="Was Derived From" fullWidth>
        <TextInput
          source="properties.prov:wasDerivedFrom.@id"
          label="Source Entity URI"
          helperText='The URI of the entity from which the dataset was derived. E.g., "https://dataspace.example.org/assets/weather-dataset-001/v2.0"'
          fullWidth
        />
      </Labeled>
      <Labeled label="Was Generated By" fullWidth>
        <TextInput
          source="properties.prov:wasGeneratedBy.dct:description"
          label="Activity Description"
          helperText='A description of the activity that generated the dataset. E.g., "Automated aggregation of IoT sensor data from WeatherNet nodes."'
          multiline
          fullWidth
        />
      </Labeled>
      <Labeled label="Was Attributed To" fullWidth>
        <TextInput
          source="properties.prov:wasAttributedTo.@id"
          label="Agent URI"
          helperText='The URI of the agent that the dataset is attributed to. E.g., "https://example.org/org/EnviroLab"'
          fullWidth
        />
      </Labeled>
    </Box>
  );
};
