import React from "react";
import {
  Typography,
  Box,
  List,
  ListItem,
  ListItemText,
} from "@mui/material";
import AccountTreeIcon from "@mui/icons-material/AccountTree";

interface ProvenanceTabProps {
  dataset: any;
}

export const ProvenanceTab: React.FC<ProvenanceTabProps> = ({ dataset }) => {
  const renderMetadataSection = (fields: any[]) => {
    const availableFields = fields.filter((field) => field.value);
    if (availableFields.length === 0) return null;

    return (
      <Box sx={{ mb: 3 }}>
        <List disablePadding>
          {availableFields.map((field, index) => (
            <ListItem key={index} disablePadding sx={{ mb: 1 }}>
              <ListItemText
                primary={
                  field.icon ? (
                    <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                      {field.icon}
                      <Typography variant="body2" fontWeight="medium">
                        {field.label}
                      </Typography>
                    </Box>
                  ) : (
                    <Typography variant="body2" fontWeight="medium">
                      {field.label}
                    </Typography>
                  )
                }
                secondary={field.value}
              />
            </ListItem>
          ))}
        </List>
      </Box>
    );
  };

  return (
    <Box>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Information about the origin and history of this asset based on the
        PROV-O Ontology.
      </Typography>

      {renderMetadataSection([
        {
          label: "Was Derived From",
          value: dataset["http://www.w3.org/ns/prov#wasDerivedFrom"]
            ? typeof dataset["http://www.w3.org/ns/prov#wasDerivedFrom"] ===
              "object"
              ? dataset["http://www.w3.org/ns/prov#wasDerivedFrom"]["@id"] ||
                "Source entity specified"
              : dataset["http://www.w3.org/ns/prov#wasDerivedFrom"]
            : null,
        },
        {
          label: "Was Generated By",
          value: dataset["http://www.w3.org/ns/prov#wasGeneratedBy"]
            ? typeof dataset["http://www.w3.org/ns/prov#wasGeneratedBy"] ===
              "object"
              ? dataset["http://www.w3.org/ns/prov#wasGeneratedBy"][
                  "dct:description"
                ] || "Activity specified"
              : dataset["http://www.w3.org/ns/prov#wasGeneratedBy"]
            : null,
        },
        {
          label: "Was Attributed To",
          value: dataset["http://www.w3.org/ns/prov#wasAttributedTo"]
            ? typeof dataset["http://www.w3.org/ns/prov#wasAttributedTo"] ===
              "object"
              ? dataset["http://www.w3.org/ns/prov#wasAttributedTo"]["@id"] ||
                "Agent specified"
              : dataset["http://www.w3.org/ns/prov#wasAttributedTo"]
            : null,
        },
      ])}
    </Box>
  );
};
